use rand::prelude::SliceRandom;

const ADJECTIVES: &[&str] = &[
    "admiring",
    "adoring",
    "affectionate",
    "agile",
    "agitated",
    "amazing",
    "ancient",
    "angry",
    "arctic",
    "atomic",
    "awesome",
    "beautiful",
    "blissful",
    "bold",
    "boring",
    "brave",
    "busy",
    "charming",
    "chill",
    "clever",
    "compassionate",
    "competent",
    "condescending",
    "confident",
    "cool",
    "cosmic",
    "cranky",
    "crazy",
    "cryptic",
    "cunning",
    "daring",
    "dazzling",
    "determined",
    "distracted",
    "dreamy",
    "eager",
    "ecstatic",
    "elastic",
    "elated",
    "elegant",
    "eloquent",
    "epic",
    "exciting",
    "fearless",
    "fervent",
    "festive",
    "fierce",
    "flamboyant",
    "focused",
    "friendly",
    "frosty",
    "funny",
    "gallant",
    "gentle",
    "gifted",
    "golden",
    "goofy",
    "gracious",
    "great",
    "happy",
    "hardcore",
    "heuristic",
    "hopeful",
    "humble",
    "hungry",
    "hyper",
    "infallible",
    "inspiring",
    "intelligent",
    "interesting",
    "jolly",
    "jovial",
    "keen",
    "kind",
    "laughing",
    "legendary",
    "loving",
    "lucid",
    "lunar",
    "magical",
    "mellow",
    "mighty",
    "modest",
    "musing",
    "mystifying",
    "naughty",
    "nervous",
    "nice",
    "nifty",
    "nimble",
    "nostalgic",
    "objective",
    "optimistic",
    "peaceful",
    "pedantic",
    "pensive",
    "polished",
    "practical",
    "priceless",
    "pristine",
    "quantum",
    "quirky",
    "quizzical",
    "radiant",
    "recursing",
    "relaxed",
    "reverent",
    "romantic",
    "rugged",
    "rustic",
    "sad",
    "serene",
    "sharp",
    "silly",
    "sleepy",
    "solar",
    "spicy",
    "spirited",
    "stealthy",
    "stellar",
    "stoic",
    "strange",
    "stupefied",
    "sturdy",
    "suspicious",
    "sweet",
    "swift",
    "synthetic",
    "tender",
    "thirsty",
    "tiny",
    "tropical",
    "trusting",
    "turbo",
    "unruffled",
    "upbeat",
    "vibrant",
    "vigilant",
    "vigorous",
    "vivid",
    "volcanic",
    "whimsical",
    "witty",
    "wizardly",
    "wonderful",
    "xenodochial",
    "youthful",
    "zealous",
    "zen",
];

const EMOJIS: &[&str] = &[
    // Animals - mammals
    "🐵", "🐒", "🦍", "🦧", "🐶", "🐕", "🦮", "🐩", "🐺", "🦊", "🦝", "🐱", "🐈", "🦁", "🐯", "🐅",
    "🐆", "🐴", "🐎", "🦄", "🦓", "🦌", "🐮", "🐂", "🐃", "🐄", "🐷", "🐖", "🐗", "🐽", "🐏", "🐑",
    "🐐", "🐪", "🐫", "🦙", "🦒", "🐘", "🦏", "🦛", "🐭", "🐁", "🐀", "🐹", "🐰", "🐇", "🦔", "🦇",
    "🐻", "🐨", "🐼", "🦥", "🦦", "🦨", "🦘", "🦡", "🐾", "🦬", "🦣", "🦫", "🦭",
    // Animals - birds
    "🦃", "🐔", "🐓", "🐣", "🐤", "🐥", "🐦", "🐧", "🦅", "🦆", "🦢", "🦉", "🦩", "🦚", "🦜", "🦤", "🪶",
    // Animals - reptiles, amphibians, marine
    "🐸", "🐊", "🐢", "🦎", "🐍", "🐲", "🐉", "🦕", "🦖", "🐳", "🐋", "🐬", "🐟", "🐠", "🐡", "🦈", "🐙",
    // Animals - invertebrates
    "🐚", "🐌", "🦋", "🐛", "🐜", "🐝", "🐞", "🦗", "🦂", "🦟", "🦠",
    // Plants & flowers
    "💐", "🌸", "💮", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷", "🌱", "🌲", "🌳", "🌴", "🌵", "🌾", "🌿",
    "🍀", "🍁", "🍂", "🍃", "🪷", "🪻", "🪸", "🪺",
    // Fruits
    "🍇", "🍈", "🍉", "🍊", "🍋", "🍌", "🍍", "🥭", "🍎", "🍏", "🍐", "🍑", "🍒", "🍓", "🥝", "🍅", "🥥",
    // Vegetables
    "🥑", "🍆", "🥔", "🥕", "🌽", "🥒", "🥬", "🥦", "🧄", "🧅", "🍄", "🥜", "🌰",
    // Food & drink
    "🍞", "🥐", "🥖", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖", "🍗", "🥩", "🥓", "🍔", "🍟", "🍕", "🌭",
    "🥪", "🌮", "🌯", "🥙", "🧆", "🥚", "🍳", "🥘", "🍲", "🥣", "🥗", "🍿", "🧈", "🧂", "🥫", "🍱",
    "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢", "🍣", "🍤", "🍥", "🥮", "🍡", "🥟", "🥠", "🥡",
    // Seafood
    "🦀", "🦞", "🦐", "🦑", "🦪",
    // Weather & sky
    "⛅", "🌧", "🌩", "🌪", "🌈", "🌙", "⭐", "🌟", "💫",
    // Celestial
    "🪐", "🌍", "🌎", "🌏", "🌑", "🌕",
    // Objects & tools
    "🔑", "🔮", "🧲", "🪄", "🧿", "🎲", "🧩", "🪁", "🏮",
    // Vehicles
    "🚀", "🛸", "⛵", "🚂", "🎠",
    // Sports & music
    "⚽", "🏀", "🎯", "🏆", "🥇", "🎸", "🥁", "🎺", "🎻",
    // Elements & sparkle
    "💎", "🔥", "⚡", "💧", "🧊", "✨", "💥",
    // Buildings & landmarks
    "🏰", "🗼", "🗿", "🏯",
];

fn main() {
    let mut rng = rand::thread_rng();
    let emoji = EMOJIS.choose(&mut rng).unwrap();
    let adjective = ADJECTIVES.choose(&mut rng).unwrap();
    println!("{adjective}-{emoji}")
}
